"""HTML report generation for Task 3 chaos analysis."""
from pathlib import Path
import sys

import pandas as pd
from plotly.offline import get_plotlyjs

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src import chaos_metrics, preprocessing, visualization

def generate_task3_report(
    data_path: Path,
    output_path: Path,
    start_hour: int = 8,
    end_hour: int = 22,
) -> None:
    """Generate comprehensive HTML report."""
    print(f"Generating HTML report from {data_path}...")
    
    # 1. Load Data
    df = pd.read_parquet(data_path)
    if "dt" not in df.columns:
        raise KeyError("dt column is required")
    df = df.copy()
    df["dt"] = pd.to_datetime(df["dt"])
    if "hour_index" not in df.columns:
        df["hour_index"] = df["dt"].dt.hour

    df_day = preprocessing.filter_daytime_hours(df, "hour_index", start=start_hour, end=end_hour)
    hourly_series = df_day["sales"].to_numpy()
    
    # 2. Compute Metrics (Hourly only, as Daily is too short)
    print("Computing Chaos Metrics (Hourly)...")
    hurst_res = chaos_metrics.hurst_rs_details(hourly_series)
    d2_res = chaos_metrics.correlation_dimension_details(hourly_series)
    
    # 3. Generate Figures
    print("Generating Plots...")
    # Time Series
    fig_ts = visualization.plot_time_series_with_stockouts(
        df_day, time_col="dt", sales_col="sales", stockout_col="is_stockout"
    )
    
    # Phase Portrait
    fig_phase = visualization.plot_phase_portrait(hourly_series, delay=1)
    
    # Hurst Plot
    if hurst_res.get("valid"):
        fig_hurst = visualization.plot_hurst_fit(hurst_res)
    else:
        fig_hurst = None
        
    # D2 Plot
    if d2_res.get("valid"):
        fig_d2 = visualization.plot_correlation_dim(d2_res)
    else:
        fig_d2 = None

    # 4. Compile HTML
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>Systems Theory: Chaos Analysis Report</title>
        <style>
            body {{ font-family: sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }}
            h1, h2 {{ color: #2c3e50; }}
            .metric-card {{ background: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px; }}
            .plot-container {{ margin-bottom: 40px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
        </style>
        <script type="text/javascript">
            {get_plotlyjs()}
        </script>
    </head>
    <body>
        <h1>Task 3: Chaos Theory Analysis</h1>
        <p><b>Dataset:</b> FreshRetailNet-50K (Golden Sample)</p>
        <p><b>Analysis Window:</b> {start_hour}:00 - {end_hour}:00 (Daytime hours only)</p>
        
        <div class="metric-card">
            <h2>Computed Metrics</h2>
            <ul>
                <li><b>Hurst Exponent (H):</b> {hurst_res.get('H', 0.0):.4f} 
                    (R² = {hurst_res.get('r2', 0.0):.4f})
                    <br><i>Interpretation:</i> {interpret_hurst(hurst_res.get('H', 0.5))}
                </li>
                <li><b>Correlation Dimension (D2):</b> {d2_res.get('D2', 0.0):.4f}
                    (R² = {d2_res.get('r2', 0.0):.4f})
                    <br><i>Interpretation:</i> Fractal dimension indicating {interpret_d2(d2_res.get('D2', 0.0))} degrees of freedom.
                </li>
            </ul>
        </div>

        <h2>1. Time Series Dynamics</h2>
        <div class="plot-container">{fig_to_html(fig_ts)}</div>

        <h2>2. Phase Space Reconstruction</h2>
        <p>Visualization of the attractor in 2D embedding (x(t) vs x(t+1)).</p>
        <div class="plot-container">{fig_to_html(fig_phase)}</div>

        <h2>3. R/S Analysis (Hurst Estimation)</h2>
        <p>Log-Log plot of Rescaled Range vs Time Scale.</p>
        <div class="plot-container">{fig_to_html(fig_hurst)}</div>

        <h2>4. Correlation Sum (D2 Estimation)</h2>
        <p>Log-Log plot of Correlation Integral C(r) vs Radius r.</p>
        <div class="plot-container">{fig_to_html(fig_d2)}</div>
        
        <hr>
        <p><i>Generated by Systems Theory Pipeline</i></p>
    </body>
    </html>
    """
    
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    
    print(f"Report saved to: {output_path.resolve()}")

def interpret_hurst(h):
    if h < 0.45: return "Anti-persistent (Mean reverting)"
    if 0.45 <= h <= 0.55: return "Random Walk (Stochastic)"
    return "Persistent (Trending/Memory)"

def interpret_d2(d2):
    if d2 < 0.1: return "Fixed Point (Static)"
    if d2 < 1.1: return "Limit Cycle (Periodic)"
    return "Low-dimensional Chaos or Strange Attractor"

def fig_to_html(fig):
    if fig is None:
        return "<p><i>Plot not available (insufficient data)</i></p>"
    return fig.to_html(full_html=False, include_plotlyjs=False)

if __name__ == "__main__":
    # Test run
    generate_task3_report(
        Path("data/golden_sample.parquet"),
        Path("docs/reports/task3_chaos_report.html")
    )